function [imgDirs, outputDirs] = generatePaths(dataset, method)
    %% constants
    cjdataBase = 'E:\eDocs\PhD\Y1S1\ELEC523\Project\1512427\brainTumorDataPublic_1-766\';
    
    bratsBase = 'E:\eDocs\PhD\Y1S1\ELEC523\Project\MICCAI_BraTS_2019_Data_Training\MICCAI_BraTS_2019_Data_Training\HGG\';
    bratsList = { ...
        'BraTS19_CBICA_ATD_1', ...
        'BraTS19_CBICA_ATF_1', ...
        'BraTS19_CBICA_ATN_1', ...
        'BraTS19_CBICA_AAB_1', ...
        'BraTS19_CBICA_AAG_1', ...
        'BraTS19_CBICA_AAL_1', ...
        'BraTS19_CBICA_AAP_1', ...
        'BraTS19_CBICA_ABB_1', ...
        'BraTS19_CBICA_ABE_1', ...
        'BraTS19_CBICA_ABM_1', ...
        'BraTS19_CBICA_ABN_1', ...
        'BraTS19_CBICA_ABO_1', ...
        'BraTS19_CBICA_ABY_1', ...
        'BraTS19_CBICA_ALN_1', ...
        'BraTS19_CBICA_ALU_1', ...
        'BraTS19_CBICA_ALX_1', ...
        'BraTS19_CBICA_AME_1', ...
        'BraTS19_CBICA_AMH_1', ...
        'BraTS19_CBICA_ANG_1', ...
        'BraTS19_CBICA_ANI_1', ...
        'BraTS19_CBICA_ANP_1', ...
        'BraTS19_CBICA_ANV_1', ...
        'BraTS19_CBICA_ANZ_1', ...
        'BraTS19_CBICA_AOC_1', ...
        'BraTS19_CBICA_AOD_1', ...
        'BraTS19_CBICA_AOH_1', ...
        'BraTS19_CBICA_AOO_1', ...
        'BraTS19_CBICA_AOP_1', ...
        'BraTS19_CBICA_AOS_1', ...
        'BraTS19_CBICA_AOZ_1', ...
        'BraTS19_CBICA_APK_1', ...
        'BraTS19_CBICA_APR_1', ...
        'BraTS19_CBICA_APY_1', ...
        'BraTS19_CBICA_APZ_1', ...
        'BraTS19_CBICA_AQA_1', ...
        'BraTS19_CBICA_AQD_1', ...
        'BraTS19_CBICA_AQG_1', ...
        'BraTS19_CBICA_AQJ_1', ...
        'BraTS19_CBICA_AQN_1', ...
        'BraTS19_CBICA_AQO_1', ...
        'BraTS19_CBICA_AQP_1', ...
        'BraTS19_CBICA_AQQ_1', ...
        'BraTS19_CBICA_AQR_1', ...
        'BraTS19_CBICA_AQT_1', ...
        'BraTS19_CBICA_AQU_1', ...
        'BraTS19_CBICA_AQV_1', ...
        'BraTS19_CBICA_AQY_1', ...
        'BraTS19_CBICA_AQZ_1', ...
        'BraTS19_CBICA_ARF_1', ...
        'BraTS19_CBICA_ARW_1'
    };
    
    cjdataOutputBase = 'E:\eDocs\PhD\Y1S1\ELEC523\Project\results\cjdata\';
    bratsOutputBase = 'E:\eDocs\PhD\Y1S1\ELEC523\Project\results\brats\';
    
    %% create folders
    if ~exist(cjdataOutputBase, 'dir')
       mkdir(cjdataOutputBase)
    end
    
    if ~exist(bratsOutputBase, 'dir')
       mkdir(bratsOutputBase)
    end
    
    %% generate paths
    imgDirs = {};
    outputDirs = {};
    
    switch dataset
        case 'cjdata'
            for i = 1:30
                imgDirs{end + 1} = char(strcat(cjdataBase, '\', num2str(i), '.mat')); % load the mat name directly
                outputDirs{end + 1} = char(strcat(cjdataOutputBase, '\', method, '_', num2str(i)));
            end
        case 'brats'
            for p = bratsList
                imgDirs{end + 1} = char(strcat(bratsBase, '\', p, '\', p)); % load the name up to the last underline
                outputDirs{end + 1} = char(strcat(bratsOutputBase, '\', method, '_@@@_', p)); % @@@ for replacing
            end
        otherwise
            error('Incorrect dataset!');
    end
end